### ISSUE TITLE
writing microsd for novasom P fail if "Number of ext3 user partitions" is set to 1

### ISSUE THREAD

**Issue by Gab010** [NovasomIndustries/NOVAembed#1]
Writing microsd for novasom P fail if "Number of ext3 user partitions" is set to 1. 
See attached files. On console is displayed "what_i_see_on_console"; the log is called "uSD_Write".
[what_i_see_on_console.txt](https://github.com/NovasomIndustries/NOVAembed/files/538711/what_i_see_on_console.txt)
[uSD_Write.txt](https://github.com/NovasomIndustries/NOVAembed/files/538712/uSD_Write.txt)

**Comment by NovasomIndustries** [comment]
Solved.

**Comment by NovasomIndustries** [comment]
The bug was in flashP script. Solved now, was a typo in the part that writes a single user partition. Test and, if ok, remove the bug

**Comment by Gab010** [comment]
fixed
