### ISSUE TITLE
In EasyPin, "Unable to open file" message is displayed just after saving bspf file

### ISSUE THREAD

**Issue by Gab010** [NovasomIndustries/NOVAembed#10]
- Run NOVAembed
- Select "P BSP factory", Run P_EasyPin
- Check something
- Click "Generate bspf file"
- Hit a name
- Click "Save"
- "Unable to open file - no such file or directory" message is displayed (2 times)
- bspf file is properly saved

NOVAembed version 1.0.4.1.rc6

**Comment by NovasomIndustries** [comment]
No, it runs fine
