### ISSUE TITLE
Inconsistent pinout in P BSP factory

### ISSUE THREAD

**Issue by Gab010** [NovasomIndustries/NOVAembed#2]
In P BSP factory tab, the pinout figure is inconsistent with the board.
NOVAembed version 1.0.4 rc3

**Comment by NovasomIndustries** [comment]
Which pins are inconsistent ?

**Comment by Gab010** [comment]
CONSOLE_TX and CONSOLE_RX are inverted

Gabriele Martini

Novasis Ingegneria S.r.l.
10048 Vinovo (TO) via Orbassano, 2A
Phone + 39 011 9004003 r.a. int. 301

skype:  gmartini.novasis
www.novasomindustries.com
www.novasis.it

 This communication contains confidential information and is intended for the named recipient(s) only. If you believe that you have received it in error or that you are not the intended recipient, do not print, copy, disseminate or use this information in any way, and notify this error to the sender.
________________________________
Da: Novasom Industries [notifications@github.com]
Inviato: giovedì 15 dicembre 2016 14.56
A: NovasomIndustries/NOVAembed
Cc: Gabriele Martini; Author
Oggetto: Re: [NovasomIndustries/NOVAembed] Inconsistent pinout in P BSP factory (#2)


Which pins are inconsistent ?

**Comment by NovasomIndustries** [comment]
Mmm ... there are no console pin on newer boards, so maybe we can close this ...

**Comment by Gab010** [comment]
pin 13 and pin 14 are for console on P BSP factory. If there are no console pin, pinout is inconsistent anycase

**Comment by NovasomIndustries** [comment]
Ok, fixed
