### ISSUE TITLE
Issue when launching "Buildroot Menu Config" for new file system

### ISSUE THREAD

**Issue by Gab010** [NovasomIndustries/NOVAembed#3]
Generate a new file system for NOVAsom P board:
- Open "Boot Kernel FileSystem" tab
- Set "Board": "P Series"
- In File System, let empty the field "Select an existing file system"
- Set "Select configuration": "PClass_Buildroot_Gstreamer.config"
- Edit "New File System Name" (no spaces in the string, no already existing name)
- Click "Generate"
- Click "Buildroot Menu Config"
- "File system name is empty" error is displayed

NOVAembed version 1.0.4 rc3

**Comment by NovasomIndustries** [comment]
Fixed, changed in rc4
