### ISSUE TITLE
Duplicated item in File System Configurations list

### ISSUE THREAD

**Issue by Gab010** [NovasomIndustries/NOVAembed#4]
-    Open "Boot Kernel FileSystem" tab
-    Set "Board": "P Series"
-    In File System, let empty the field "Select an existing file system"
-    Set "Select configuration": "PClass_Buildroot_Base.config"
-    Click "Generate"
-    Click "Buildroot Menu Config"
-    Add something (for example libts)
-    Save, exit
-    Click "Deploy"
-    Open the "Select Configuration" list: "PClass_Buildroot_Base.config" item is duplicated

NOVAembed version 1.0.4.1 rc3

**Comment by NovasomIndustries** [comment]
No way to remove this. Please close this, is a QT issue
