### ISSUE TITLE
Video output selected by NOVAembed interface but not affect boot setting

### ISSUE THREAD

**Issue by Gab010** [NovasomIndustries/NOVAembed#5]
Video output selecetd by NOVAembed interface, but not affect boot setting.

- Set "Board": "P Series"
- In File System, Select an existing file system: click "Browse"
- Choose for example "Gstreamer"
- Click "Deploy"
- In "Write uSD" Set "Video", for example "LVDS 800x480"
- Make sure microsd is inserted and properly mounted, and "Device" is properly set
- Click "Write uSD"
- Make sure the microsd is successfully written
- Insert the microsd in NOVAsom P board, with display plugged (LVDS 800x480), console cable connected, serial terminal software running
- Power on
- Press any key to stop the countdown at boot
- Hit on console: "printenv"
- See hdmi is set as current video output

NOVAembed version 1.0.4.1 rc3

**Comment by NovasomIndustries** [comment]
Not yet implemented in u-boot. There is an HDMI bug in the kernel that prevents any HDMI initialization in the boot, otherwise the kernel hangs. So no video at boot, for now. Waiting for new kernels.

**Comment by Gab010** [comment]
closed on latest version
