### ISSUE TITLE
autorun ignored

### ISSUE THREAD

**Issue by Gab010** [NovasomIndustries/NOVAembed#6]
Autorun is ignored (it worked on SDK104, version updated at 30 october)

- make a microsd for novasom P
- create a folder named "application_storage" in the Config partition
- create a file named "AutoRun.sh" in the "application_storage" folder
- Edit "AutoRun.sh" as follow
```C
#!/bin/sh
echo siviglia
```
- save, and test the microsd card on the board
- connect console cable, power on the board, hit on console:
```C
ps
```
- see AutoRun.sh is not running

**Comment by NovasomIndustries** [comment]
Fixed, changed in rc4

**Comment by Gab010** [comment]
still open in rc4

**Comment by NovasomIndustries** [comment]
Fixed in rc5

**Comment by Gab010** [comment]
still open in rc5

**Comment by Gab010** [comment]
Still open in rc5 (updated at January 9)
two procedures tested:
Test 1. 
See first description of this issue

Test 2. 
- create the directory application_storage
```
/home/fil/Documents/application_storage
```
- Create the file AutoRun.sh in the application_storage directory, and edit as follow:
```
#!/bin/sh
echo siviglia
```
- Save and exit
- Run NOVAembed 
- Compile boot loader for P series
- Select file system: Base
- Deploy file system
- Check "Set the AutoRun"
- Press "AutoRun folder Browse"
- Choose "application_storage"
- Write uSD
- See in the "Config" partition there is no application_storage directory or AutoRun.sh file 
- Test the microsd card on the board
- connect console cable, power on the board
- Hit on console:
```
ps
```
- see AutoRun.sh is not running

**Comment by Gab010** [comment]
Fixed on rc5 (version January 10)
