### ISSUE TITLE
Unable to read dtb for s series board

### ISSUE THREAD

**Issue by Gab010** [NovasomIndustries/NOVAembed#7]
- Run NOVAembed
- Select "board": "S Series"
- Compile Boot Loader
- Select existing File System: Base
- Deploy File System
- Make DTBs
- insert microsd
- Write microsd
- Insert microsd in the NOVAesom S board (NI240613-FS01-03)
- Connect console cable, run serial terminal, power on
- See serial terminal

Console log attached. NOVAembed version 1.0.4.1 rc4
[console_log.txt](https://github.com/NovasomIndustries/NOVAembed/files/666122/console_log.txt)

**Comment by NovasomIndustries** [comment]
Yes, the BSPFactory defines the dtb to use with the board. And there is no BSPFactory for S. Should be nice to remove the selection for S boards. And for U , for now only ... Thought ?

**Comment by Gab010** [comment]
I agree; S and U should be available to be selected only when working.
