### ISSUE TITLE
AutoRun not checked in NOVAembed but written anyway on microsd

### ISSUE THREAD

**Issue by Gab010** [NovasomIndustries/NOVAembed#8]
- create the directory application_storage
```
/home/fil/Documents/application_storage
```
- Create the file AutoRun.sh in the application_storage directory, and edit as follow:
```
#!/bin/sh
echo siviglia
```
- Save and exit
- Run NOVAembed
- Compile boot loader for P series
- Select file system: Base
- Deploy file system
- Check "Set the AutoRun"
- Press "AutoRun folder Browse"
- Choose "application_storage"
- Write uSD
- See in the "Config" partition there is no application_storage directory or AutoRun.sh file
- Test the microsd card on the board
- Connect console cable, power on the board
- See AutoRun is properly working
- Run NOVAembed
- Uncheck "Set the AutoRun"
- Write the microsd
- Test the microsd card on the board
- Connect console cable, power on the board
- See AutoRun is running as it was selecetd

**Comment by Gab010** [comment]
- create the directory application_storage
```
/home/fil/Documents/application_storage
```
- Create the file AutoRun.sh in the application_storage directory, and edit as follow:
```
#!/bin/sh
echo siviglia
```
- Save and exit
- Run NOVAembed
- Compile boot loader for P series
- Select file system: Base
- Deploy file system
- Check "Set the AutoRun"
- Press "AutoRun folder Browse"
- Choose "application_storage"
- Write uSD
- Test the microsd card on the board
- Connect console cable, power on the board
- See AutoRun is properly working
- Run NOVAembed
- Uncheck "Set the AutoRun"
- Write the microsd
- See that in config partition, in application_storage folder, is written AutoRun.sh script (and will run if you test the microsd on the board)

NOVAembed version 1.0.4.1rc6

**Comment by NovasomIndustries** [comment]
Fixed. Issue not deleted so Gab will live happy ... ;-)

**Comment by Gab010** [comment]
: )

**Comment by NovasomIndustries** [comment]
Sorry, fixed now.
Please delete if confirmed
