### ISSUE TITLE
In EasyPin, already checked options are not refreshed after loading bspf file

### ISSUE THREAD

**Issue by Gab010** [NovasomIndustries/NOVAembed#9]
In EasyPin, already checked options are not refreshed after loading bspf file

- Run NOVAembed
- Run EasyPin
- Check "S2PI1" and "SPI dev on SPI 1"
- Generate bspf file, name it "conf1"
- Uncheck "SPI1" and "SPI dev on SPI 1"
- Check "SPI2" and "SPI dev on SPI 2"
- Generate bspf file, name it "conf2"
- Click "Load bspf file", choose "conf1.bspf"
- See "SPI1" and "SPI dev on SPI1" is checked (as expected), and also "SPI2" and "SPI dev on SPI 2" is checked (should be unchecked)

NOVAembed version 1.0.4.1rc5

**Comment by NovasomIndustries** [comment]
Got it, the checkboxs and editlines mus be cleared before a load. The bspf files are ok.

**Comment by shinymetal6** [comment]
Fixed
